### PR TITLE
promisify and lipstickify

### PR DESCRIPTION
**Pull request by SamVerschueren**
Any reason `travis` isn't enabled on this module? Refactored the test that should run on travis I guess.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Any reason travis isn't enabled on this module?

Probably, but don't remember. Let's try.

**Comment by sindresorhus** [comment]
👌

**Comment by SamVerschueren** [comment]
It seems we have to tweak the test a little. Any idea how we can determine the open command path?

**Comment by sindresorhus** [comment]
Already fixed

**Comment by SamVerschueren** [comment]
Wow, very clean! :heart:

**Pull request merged**
